// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Length():Promise<number>;

export function LoadBook(arg1:string):Promise<number>;

export function SelectFile():Promise<string>;
